### ISSUE TITLE
Assertion is not verification.

### ISSUE THREAD

**Issue by JoelBondurant** [madumas/ethsupply#3]
"Calculates the total amount of Eth ever issued."
https://github.com/madumas/ethsupply/blame/master/README.md#L2

Hard coding an asserted result doesn't count as a calculation in the context of verification.

https://github.com/madumas/ethsupply/blob/04e4e145e9e88eb500476dc5671ad11caf8c637e/src/ethSupply.js#L17

**Comment by madumas** [comment]
Revalidating the genesis block is out of scope of this script. It was independently verified by hundreds of persons during Ethereum launch: https://blog.ethereum.org/2015/07/27/final-steps/

You may also check out https://github.com/openethereum/openethereum/blob/master/ethcore/res/ethereum/foundation.json and calculate the initial supply yourself.
