### ISSUE TITLE
Calculate genesis supply from block 0 transactions

### ISSUE THREAD

**Issue by mutatrum** [madumas/ethsupply#5]
The genesis supply constant should not be in the code, as it can be derived from block 0 transactions.

It's also off by a bit, probably by rounding.

https://github.com/madumas/ethsupply/blob/bfb2c8388abaaa676d721afa6394103a0edfab00/src/ethSupply.js#L17

**Comment by madumas** [comment]
You can calculate it from the genesis block, but the verification of the genesis block is out of scope of script.

**Comment by mutatrum** [comment]
Similar is the block rewards with their respective block numbers. This should also come from the node itself as the current list of constants is not verification and it's not future proof. https://github.com/madumas/ethsupply/blob/bfb2c8388abaaa676d721afa6394103a0edfab00/src/ethSupply.js#L3

**Comment by madumas** [comment]
Revalidating the genesis block is out of scope of this script. It was independently verified by hundreds of persons during Ethereum launch: https://blog.ethereum.org/2015/07/27/final-steps/

You may also check out https://github.com/openethereum/openethereum/blob/master/ethcore/res/ethereum/foundation.json and calculate the initial supply yourself.

**Comment by mutatrum** [comment]
> It's also off by a bit, probably by rounding.

**Comment by madumas** [comment]
Please indicate the expected value, and for which block so I can reproduce.

**Comment by mutatrum** [comment]
No
