### ISSUE TITLE
Use exact genesis issuance

### ISSUE THREAD

**Issue by lastmjs** [madumas/ethsupply#6]
Hey! The issuance used in this script is `72009990.50`. The exact issuance in WEI is `72009990499480000000000000` and in ETH is `72009990.49948`. These values can be generated from Geth here (RLP-encoded): https://github.com/ethereum/go-ethereum/blob/48b484c5ac537d1759c9903ce81302c298f03a84/core/genesis_alloc.go Open Ethereum here (json): https://github.com/openethereum/openethereum/blob/master/ethcore/res/ethereum/foundation.json, and Nethermind (json) here: https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Chains/foundation.json

I think it's important to get this exactly right.

**Comment by madumas** [comment]
This is correct. I fixed the default value and added a method to compute it directly from a Parity/OpenEthereum foundation.json file.
