### ISSUE TITLE
Use something like BigNumber.js, do calculations in WEI

### ISSUE THREAD

**Issue by lastmjs** [madumas/ethsupply#7]
Hey, I think your calculations might start getting off as the cumulative sums increase down the blockchain. Using JavaScript's floating-point numbers is going to be inaccurate when dealing with decimal places. I recommend doing all calculations with BigNumber.js, and in WEI, then dividing by 10**18 to display the final result

**Comment by madumas** [comment]
Thanks. Switched everything to Wei using BigNumber.js to be on the safe side
