### ISSUE TITLE
Transaction rewards

### ISSUE THREAD

**Issue by alexnu** [madumas/ethsupply#9]
Hi,

Please forgive my ignorance as I'm relatively new to Ethereum. I was wondering shouldn't we include transaction fees in block reward calculation?

When looking at various [Statistics websites](https://bitinfocharts.com/ethereum/), I always see three numbers adding up to the total block reward:

static block reward + trx fees + uncle inclusion rewards + uncle rewards

![Screenshot 2021-05-03 at 2 26 09 PM](https://user-images.githubusercontent.com/3530783/116870639-89bea800-ac1b-11eb-8f0d-57348d1a40d6.png)

Why are transaction fees not included in total supply calculation?

**Comment by madumas** [comment]
Fees are not included because they are not adding to the supply. Users are paying fees to the miners, but that doesn't change the total ether supply.

This will change with EIP 1559 and this calculator will have to be updated when it gets activated.

**Comment by alexnu** [comment]
Because these are already existing coins not new ones, I think I get it now.

Thanks for taking the time to respond. Closing this now.
